name: Unit Testing by Github Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: start docker
        run: docker compose up -d

      - name: Add exec Permission
        run: chmod +x gradlew

      - name: Test with Gradle
        id: test
        run: ./gradlew test
        if: always()
